"""Shared runtime package for controlled Hotel OTA capabilities."""

from __future__ import annotations

from runtime.live_contract_patch import install as _install_live_contract_patch
from runtime.historical_report_scope_patch import (
    install_post as _install_historical_report_scope_post_patch,
    install_pre as _install_historical_report_scope_pre_patch,
)
from runtime.s2_historical_daily_source_patch import (
    install as _install_s2_historical_daily_source_patch,
)
from runtime.s2_historical_flow_snapshot_patch import (
    install as _install_s2_historical_flow_snapshot_patch,
)
from runtime.s14_runtime_patch import install as _install_s14_runtime_patch
from runtime.s13_runtime_patch import install as _install_s13_runtime_patch
from runtime.s15_s16_runtime_patch import install as _install_s15_s16_runtime_patch
from runtime.s15_s16_ai_analysis_patch import install as _install_s15_s16_ai_analysis_patch
from runtime.s15_s16_ai_presentation_patch import install as _install_s15_s16_ai_presentation_patch
from runtime.s15_s16_spec_alignment_patch import install as _install_s15_s16_spec_alignment_patch
from runtime.s15_s16_spec_followup_patch import install as _install_s15_s16_spec_followup_patch
from runtime.s15_s16_presentation_completeness_patch import install as _install_s15_s16_presentation_completeness_patch
from runtime.s15_s16_object_series_patch import install as _install_s15_s16_object_series_patch
from runtime.s15_s16_template_advisory_patch import install as _install_s15_s16_template_advisory_patch
from runtime.s15_s16_advisory_boundary_patch import install as _install_s15_s16_advisory_boundary_patch
from runtime.s15_s16_technical_spec_patch import install as _install_s15_s16_technical_spec_patch
from runtime.s15_s16_compact_output_patch import install as _install_s15_s16_compact_output_patch
from runtime.s15_s16_data_correctness_patch import install as _install_s15_s16_data_correctness_patch
from runtime.s15_s16_current_batch_patch import install as _install_s15_s16_current_batch_patch
from runtime.s15_s16_stale_batch_patch import install as _install_s15_s16_stale_batch_patch
from runtime.s15_s16_cache_freshness_patch import install as _install_s15_s16_cache_freshness_patch
from runtime.s15_market_metric_patch import install as _install_s15_market_metric_patch
from runtime.s15_s16_complete_output_patch import install as _install_s15_s16_complete_output_patch
from runtime.s15_price_scope_patch import install as _install_s15_price_scope_patch
from runtime.s15_baseline_detail_patch import install as _install_s15_baseline_detail_patch
from runtime.s15_matrix_contract_patch import install as _install_s15_matrix_contract_patch
from runtime.s15_platform_period_patch import install as _install_s15_platform_period_patch
from runtime.s15_s16_prearrival_fact_patch import install as _install_s15_s16_prearrival_fact_patch
from runtime.s17_feishu_route_patch import install as _install_s17_feishu_route_patch
from runtime.s17_room_type_name_patch import install as _install_s17_room_type_name_patch
from runtime.s17_public_text_patch import install as _install_s17_public_text_patch
from runtime.s13_data_rules_patch import install as _install_s13_data_rules_patch
from runtime.s01_s17_exact_route_patch import install as _install_s01_s17_exact_route_patch
from runtime.s09_baseline_classification_patch import install as _install_s09_baseline_classification_patch
from runtime.s13_pending_performance_patch import install as _install_s13_pending_performance_patch
from runtime.s13_feishu_route_fix_patch import install as _install_s13_feishu_route_fix_patch
from runtime.s15_s16_responsibility_patch import install as _install_s15_s16_responsibility_patch
from runtime.s15_baseline_only_patch import install as _install_s15_baseline_only_patch
from runtime.s15_cache_materialization_patch import install as _install_s15_cache_materialization_patch
from runtime.s16_skill_delivery_patch import install as _install_s16_skill_delivery_patch
from runtime.meituan_activity_net_price_patch import install as _install_meituan_activity_net_price_patch
from runtime.meituan_activity_net_price_output_patch import install as _install_meituan_activity_net_price_output_patch
from runtime.s16_meituan_projection_advisory_patch import install as _install_s16_meituan_projection_advisory_patch
from runtime.s5_final_display_contract_patch import install as _install_s5_final_display_contract_patch
from runtime.s16_platform_pay_order_primary_patch import install as _install_s16_platform_pay_order_primary_patch
from runtime.s5_s16_market_heat_sync_patch import install as _install_s5_s16_market_heat_sync_patch
from runtime.s5_route_restore_patch import install as _install_s5_route_restore_patch
from runtime.s5_product_type_filter_patch import install as _install_s5_product_type_filter_patch
from runtime.s5_s15_baseline_contract_patch import install as _install_s5_s15_baseline_contract_patch
from runtime.s15_s16_final_convergence_patch import install as _install_s15_s16_final_convergence_patch
from runtime.s15_room_hourly_readability_patch import install as _install_s15_room_hourly_readability_patch
from runtime.s16_room_net_price_comparison_patch import install as _install_s16_room_net_price_comparison_patch
from runtime.s09_metric_fallback_patch import install as _install_s09_metric_fallback_patch
from runtime.s09_feishu_presentation_patch import install as _install_s09_feishu_presentation_patch
from runtime.s16_price_reference_readiness_patch import install as _install_s16_price_reference_readiness_patch
from runtime.s15_s16_price_comparison_scope_patch import install as _install_s15_s16_price_comparison_scope_patch
from runtime.s4_market_heat_contract_patch import install as _install_s4_market_heat_contract_patch
from runtime.p0_route_ownership_patch import install as _install_p0_route_ownership_patch
from runtime.s14_retirement_patch import install as _install_s14_retirement_patch
from runtime.s2_daily_report_route_patch import install as _install_s2_daily_report_route_patch
from runtime.owner_role_permission_patch import install as _install_owner_role_permission_patch
from runtime.s11_readonly_plan_patch import install as _install_s11_readonly_plan_patch
from runtime.s11_promotion_execution_patch import install as _install_s11_promotion_execution_patch
from runtime.s11_per_plan_recommendation_patch import install as _install_s11_per_plan_recommendation_patch
from runtime.s6_price_bounds_bypass_patch import install as _install_s6_price_bounds_bypass_patch
from runtime.feishu_production_output_boundary_patch import install as _install_feishu_production_output_boundary_patch

_install_live_contract_patch()
_install_historical_report_scope_pre_patch()
_install_s2_historical_daily_source_patch()
_install_s2_historical_flow_snapshot_patch()
_install_s14_runtime_patch()
_install_s13_runtime_patch()
_install_s15_s16_runtime_patch()
_install_s15_s16_ai_analysis_patch()
_install_s15_s16_ai_presentation_patch()
_install_s15_s16_spec_alignment_patch()
_install_s15_s16_spec_followup_patch()
_install_s15_s16_presentation_completeness_patch()
_install_s15_s16_object_series_patch()
_install_s15_s16_template_advisory_patch()
_install_s15_s16_advisory_boundary_patch()
_install_s15_s16_technical_spec_patch()
_install_s15_s16_compact_output_patch()
_install_s15_s16_data_correctness_patch()
_install_s15_s16_current_batch_patch()
_install_s15_s16_stale_batch_patch()
_install_s15_s16_cache_freshness_patch()
_install_s15_market_metric_patch()
_install_s15_s16_complete_output_patch()
_install_s15_price_scope_patch()
_install_s15_baseline_detail_patch()
_install_s15_matrix_contract_patch()
_install_s15_platform_period_patch()
_install_s15_s16_prearrival_fact_patch()
_install_s17_feishu_route_patch()
_install_s17_room_type_name_patch()
_install_s17_public_text_patch()
_install_s13_data_rules_patch()
_install_s01_s17_exact_route_patch()
_install_s09_baseline_classification_patch()
_install_s13_pending_performance_patch()
_install_s15_s16_responsibility_patch()
_install_s15_baseline_only_patch()
_install_s15_cache_materialization_patch()
_install_s16_skill_delivery_patch()
_install_meituan_activity_net_price_patch()
_install_meituan_activity_net_price_output_patch()
_install_s16_meituan_projection_advisory_patch()
_install_s16_platform_pay_order_primary_patch()
_install_s5_s16_market_heat_sync_patch()
_install_historical_report_scope_post_patch()
_install_s5_route_restore_patch()
_install_s5_product_type_filter_patch()
_install_s5_s15_baseline_contract_patch()
_install_s15_s16_final_convergence_patch()
_install_s15_room_hourly_readability_patch()
_install_s16_room_net_price_comparison_patch()
_install_s09_metric_fallback_patch()
_install_s09_feishu_presentation_patch()
_install_s16_price_reference_readiness_patch()
_install_s15_s16_price_comparison_scope_patch()
_install_s4_market_heat_contract_patch()
_install_p0_route_ownership_patch()
_install_s14_retirement_patch()
_install_s2_daily_report_route_patch()
_install_owner_role_permission_patch()
_install_s5_final_display_contract_patch()
_install_s11_readonly_plan_patch()
_install_s11_promotion_execution_patch()
_install_s11_per_plan_recommendation_patch()
_install_s6_price_bounds_bypass_patch()
_install_feishu_production_output_boundary_patch()
_install_s13_feishu_route_fix_patch()
_install_s13_pending_performance_patch()

del _install_live_contract_patch
del _install_historical_report_scope_pre_patch
del _install_historical_report_scope_post_patch
del _install_s2_historical_daily_source_patch
del _install_s2_historical_flow_snapshot_patch
del _install_s14_runtime_patch
del _install_s13_runtime_patch
del _install_s15_s16_runtime_patch
del _install_s15_s16_ai_analysis_patch
del _install_s15_s16_ai_presentation_patch
del _install_s15_s16_spec_alignment_patch
del _install_s15_s16_spec_followup_patch
del _install_s15_s16_presentation_completeness_patch
del _install_s15_s16_object_series_patch
del _install_s15_s16_template_advisory_patch
del _install_s15_s16_advisory_boundary_patch
del _install_s15_s16_technical_spec_patch
del _install_s15_s16_compact_output_patch
del _install_s15_s16_data_correctness_patch
del _install_s15_s16_current_batch_patch
del _install_s15_s16_stale_batch_patch
del _install_s15_s16_cache_freshness_patch
del _install_s15_market_metric_patch
del _install_s15_s16_complete_output_patch
del _install_s15_price_scope_patch
del _install_s15_baseline_detail_patch
del _install_s15_matrix_contract_patch
del _install_s15_platform_period_patch
del _install_s15_s16_prearrival_fact_patch
del _install_s17_feishu_route_patch
del _install_s17_room_type_name_patch
del _install_s17_public_text_patch
del _install_s13_data_rules_patch
del _install_s01_s17_exact_route_patch
del _install_s09_baseline_classification_patch
del _install_s13_pending_performance_patch
del _install_s13_feishu_route_fix_patch
del _install_s15_s16_responsibility_patch
del _install_s15_baseline_only_patch
del _install_s15_cache_materialization_patch
del _install_s16_skill_delivery_patch
del _install_meituan_activity_net_price_patch
del _install_meituan_activity_net_price_output_patch
del _install_s16_meituan_projection_advisory_patch
del _install_s5_final_display_contract_patch
del _install_s16_platform_pay_order_primary_patch
del _install_s5_s16_market_heat_sync_patch
del _install_s5_route_restore_patch
del _install_s5_product_type_filter_patch
del _install_s5_s15_baseline_contract_patch
del _install_s15_s16_final_convergence_patch
del _install_s15_room_hourly_readability_patch
del _install_s16_room_net_price_comparison_patch
del _install_s09_metric_fallback_patch
del _install_s09_feishu_presentation_patch
del _install_s16_price_reference_readiness_patch
del _install_s15_s16_price_comparison_scope_patch
del _install_s4_market_heat_contract_patch
del _install_p0_route_ownership_patch
del _install_s14_retirement_patch
del _install_s2_daily_report_route_patch
del _install_owner_role_permission_patch
del _install_s11_readonly_plan_patch
del _install_s11_promotion_execution_patch
del _install_s11_per_plan_recommendation_patch
del _install_s6_price_bounds_bypass_patch
del _install_feishu_production_output_boundary_patch
